{{- if eq (.Values.server.config.upstreamAuthority.disk.enabled | toString) "true"}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spire.fullname" . }}-upstream-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire.server.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.server.config.upstreamAuthority.disk.certificate | toYaml | indent 2 }}
  tls.key: {{ .Values.server.config.upstreamAuthority.disk.key | toYaml | indent 2 }}
  {{- if ne .Values.server.config.upstreamAuthority.disk.bundle ""}}
  bundle.crt: {{ .Values.server.config.upstreamAuthority.disk.bundle | toYaml | indent 2 }}
  {{- end }}
{{- end }}
