{{- $root := . }}
{{- with .Values.server.config.upstreamAuthority.disk }}
{{- if eq (.enabled | toString) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spire.fullname" $root }}-upstream-ca
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "spire.server.labels" $root | nindent 4 }}
data:
  tls.crt: {{ .certificate | toYaml | indent 2 }}
  tls.key: {{ .key | toYaml | indent 2 }}
  {{- if ne .bundle ""}}
  bundle.crt: {{ .bundle | toYaml | indent 2 }}
  {{- end }}
{{- end }}
{{- end }}
